'use strict';
const $=id=>document.getElementById(id), canvas=$('view'),ctx=canvas.getContext('2d');
const R=6378137, WORLD=2*Math.PI*R;let tracks=[],areas=[],active=null,polygon=null,progress=0,playing=false,last=0,cam=null,mask=null,recorder=null,tiles=new Map(),tileFailed=false;
const project=([lon,lat])=>[R*lon*Math.PI/180,-R*Math.log(Math.tan(Math.PI/4+Math.max(-85,Math.min(85,lat))*Math.PI/360))];
const distance=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function prepare(t){t.points=t.points.filter((p,i,a)=>!i||distance(p,a[i-1])>.001);if(t.points.length<2)throw Error('Trajetória sem comprimento.');t.cum=[0];for(let i=1;i<t.points.length;i++)t.cum.push(t.cum[i-1]+distance(t.points[i-1],t.points[i]));t.total=t.cum.at(-1);return t;}
function pointAt(f){let d=f*active.total,i=1;while(i<active.cum.length-1&&active.cum[i]<d)i++;let u=(d-active.cum[i-1])/(active.cum[i]-active.cum[i-1]);let a=active.points[i-1],b=active.points[i];return {p:[a[0]+u*(b[0]-a[0]),a[1]+u*(b[1]-a[1])],i};}
const nodes=(e,n)=>Array.from(e.getElementsByTagNameNS('*',n));
function coords(text,space=false){return text.trim().split(space?/\n+/:/\s+/).filter(Boolean).map(s=>s.trim().split(space?/\s+/:/,/).map(Number)).filter(a=>a.length>=2&&Number.isFinite(a[0])&&Number.isFinite(a[1])&&Math.abs(a[0])<=180&&Math.abs(a[1])<=90).map(project);}
function estimatedAxis(ring){let c=ring.reduce((s,p)=>[s[0]+p[0]/ring.length,s[1]+p[1]/ring.length],[0,0]);let xx=0,xy=0,yy=0;for(let p of ring){let x=p[0]-c[0],y=p[1]-c[1];xx+=x*x;xy+=x*y;yy+=y*y;}let a=.5*Math.atan2(2*xy,xx-yy),v=[Math.cos(a),Math.sin(a)],n=[-v[1],v[0]];let ps=ring.map(p=>[(p[0]-c[0])*v[0]+(p[1]-c[1])*v[1],(p[0]-c[0])*n[0]+(p[1]-c[1])*n[1]]);let lo=Math.min(...ps.map(p=>p[0])),hi=Math.max(...ps.map(p=>p[0])),result=[];for(let k=0;k<=80;k++){let x=lo+(hi-lo)*(k+.001)/80.002,ys=[];for(let j=1;j<ps.length;j++){let b=ps[j],a=ps[j-1];if((a[0]<=x&&b[0]>x)||(b[0]<=x&&a[0]>x))ys.push(a[1]+(b[1]-a[1])*(x-a[0])/(b[0]-a[0]));}if(ys.length>=2){let y=(Math.min(...ys)+Math.max(...ys))/2;result.push([c[0]+x*v[0]+y*n[0],c[1]+x*v[1]+y*n[1]]);}}return result;}
function parseKML(xml){let doc=new DOMParser().parseFromString(xml,'application/xml');if(nodes(doc,'parsererror').length)throw Error('KML inválido: erro de XML.');let ts=[],as=[];for(let [i,pm] of nodes(doc,'Placemark').entries()){let name=nodes(pm,'name')[0]?.textContent.trim()||`Trajetória ${i+1}`;for(let line of nodes(pm,'LineString')){let points=coords(nodes(line,'coordinates')[0]?.textContent||'');if(points.length>1)ts.push(prepare({name,points}));}for(let track of nodes(pm,'Track')){let points=nodes(track,'coord').flatMap(n=>coords(n.textContent,true));if(points.length>1)ts.push(prepare({name,points}));}for(let p of nodes(pm,'Polygon')){let outer=nodes(p,'outerBoundaryIs')[0],ring=coords(outer?nodes(outer,'coordinates')[0]?.textContent||'':'');let holes=nodes(p,'innerBoundaryIs').map(h=>coords(nodes(h,'coordinates')[0]?.textContent||''));if(ring.length>=3){if(distance(ring[0],ring.at(-1))>0)ring.push(ring[0]);as.push({name,ring,holes});}}}if(!ts.length)for(let [i,a] of as.entries()){let points=estimatedAxis(a.ring);if(points.length>1)ts.push(prepare({name:a.name+' · eixo estimado',points,estimated:true,area:i}));}if(!ts.length)throw Error('Nenhuma linha ou polígono utilizável no KML. KMZ não é suportado nesta versão.');return {tracks:ts,areas:as};}
function setData(data){tracks=data.tracks;areas=data.areas;$('track').replaceChildren(...tracks.map((t,i)=>new Option(t.name,i)));$('area').replaceChildren(new Option('Sem polígono',-1),...areas.map((a,i)=>new Option(a.name,i)));selectTrack();}
function selectTrack(){active=tracks[+$('track').value||0];let a=active.area??areas.findIndex(a=>a.name===active.name);$('area').value=String(a);progress=0;playing=false;cam=null;selectArea();$('title').textContent=active.name;$('status').textContent=active.estimated?'Eixo estimado do polígono. Confira o percurso e use Inverter se necessário.':`${tracks.length} trajetória(s), ${areas.length} área(s). Se necessário, selecione o polígono correspondente.`;}
function selectArea(){polygon=areas[+$('area').value]||null;mask=null;if(polygon)buildMask();}
function bounds(points){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(let p of points){minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1]);}return {minX,minY,maxX,maxY,w:maxX-minX,h:maxY-minY};}
// Rasterize original geometry, then assign each covered pixel to its nearest position along the route.
function buildMask(){let b=bounds(polygon.ring),scale=600/Math.max(b.w,b.h,1),w=Math.max(1,Math.ceil(b.w*scale)),h=Math.max(1,Math.ceil(b.h*scale)),c=document.createElement('canvas');c.width=w;c.height=h;let g=c.getContext('2d');g.beginPath();for(let ring of [polygon.ring,...polygon.holes]){ring.forEach((p,i)=>g[i?'lineTo':'moveTo']((p[0]-b.minX)*scale,(p[1]-b.minY)*scale));g.closePath();}g.fill('evenodd');let data=g.getImageData(0,0,w,h),when=new Float32Array(w*h);when.fill(2);let route=Array.from({length:201},(_,i)=>pointAt(i/200).p);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let k=y*w+x;if(!data.data[k*4+3])continue;let p=[b.minX+(x+.5)/scale,b.minY+(y+.5)/scale],best=Infinity,f=0;for(let j=1;j<route.length;j++){let a=route[j-1],v=[route[j][0]-a[0],route[j][1]-a[1]],d=v[0]*v[0]+v[1]*v[1],u=d?Math.max(0,Math.min(1,((p[0]-a[0])*v[0]+(p[1]-a[1])*v[1])/d)):0,dd=(p[0]-a[0]-u*v[0])**2+(p[1]-a[1]-u*v[1])**2;if(dd<best){best=dd;f=(j-1+u)/200;}}when[k]=f;}mask={c,g,b,data,when,previous:-1,color:''};}
function demo(){let points=Array.from({length:60},(_,i)=>project([-49.65+i*.005,-25.4+i*.002+Math.sin(i/8)*.007]));let ring=[];for(let sign of [1,-1]){let ps=points.map((p,i)=>[p[0],p[1]+sign*(180+650*Math.sin(Math.PI*i/59)**2)]);ring.push(...(sign===1?ps:ps.reverse()));}ring.push(ring[0]);setData({tracks:[prepare({name:'Demonstração fictícia · Paraná',points,area:0})],areas:[{name:'Faixa fictícia · largura variável',ring,holes:[]}]});}
function tile(z,x,y,base){let n=2**z;if(y<0||y>=n)return null;x=((x%n)+n)%n;let key=`${base}/${z}/${x}/${y}`;if(!tiles.has(key)){let img=new Image();img.crossOrigin='anonymous';img.onload=()=>{img.ready=true;};img.onerror=()=>{img.failed=true;tileFailed=true;};img.src=base==='osm'?`https://tile.openstreetmap.org/${z}/${x}/${y}.png`:`https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/${z}/${y}/${x}`;tiles.set(key,img);if(tiles.size>320)tiles.delete(tiles.keys().next().value);}return tiles.get(key);}
function render(now){let dt=Math.min((now-last)/1000||0,.1);last=now;let duration=Math.max(3,Math.min(600,+$('duration').value||30));if(playing){progress=Math.min(1,progress+dt/duration);if(progress===1){playing=false;if(recorder?.state==='recording')recorder.stop();}}let w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#0d1823';ctx.fillRect(0,0,w,h);if(!active){requestAnimationFrame(render);return;}let pos=pointAt(progress),b=bounds(active.points.concat(polygon?.ring||[])),fit=Math.min(w*.75/Math.max(b.w,500),h*.58/Math.max(b.h,500)),follow=$('camera').value==='follow',scale=fit*(follow?+$('zoom').value:1),target=follow?pos.p:[(b.minX+b.maxX)/2,(b.minY+b.maxY)/2];if(!cam)cam=target.slice();let smooth=1-Math.exp(-dt*6);cam=cam.map((v,i)=>v+(target[i]-v)*smooth);let screen=p=>[(p[0]-cam[0])*scale+w/2,(p[1]-cam[1])*scale+h/2];let base=$('basemap').value;
ctx.strokeStyle='#1e3040';ctx.lineWidth=1;for(let x=0;x<w;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
if(base!=='grid'){ctx.save();if($('gray').checked)ctx.filter='grayscale(1) brightness(.62)';let z=Math.max(0,Math.min(18,Math.round(Math.log2(WORLD*scale/256)))),unit=WORLD/2**z,left=cam[0]-w/2/scale,top=cam[1]-h/2/scale;for(let x=Math.floor((left+WORLD/2)/unit);x<=Math.floor((left+w/scale+WORLD/2)/unit);x++)for(let y=Math.floor((top+WORLD/2)/unit);y<=Math.floor((top+h/scale+WORLD/2)/unit);y++){let img=tile(z,x,y,base);if(img?.ready){let p=screen([x*unit-WORLD/2,y*unit-WORLD/2]);ctx.drawImage(img,p[0],p[1],unit*scale+.5,unit*scale+.5);}}ctx.restore();}
let color=$('color').value;if(mask){if(Math.abs(mask.previous-progress)>.001||mask.color!==color){let rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16));for(let k=0;k<mask.when.length;k++){let a=k*4;mask.data.data[a]=rgb[0];mask.data.data[a+1]=rgb[1];mask.data.data[a+2]=rgb[2];mask.data.data[a+3]=progress>0&&mask.when[k]<=progress?110:0;}mask.g.putImageData(mask.data,0,0);mask.previous=progress;mask.color=color;}let p=screen([mask.b.minX,mask.b.minY]);ctx.drawImage(mask.c,p[0],p[1],mask.b.w*scale,mask.b.h*scale);}
ctx.save();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.lineJoin='round';ctx.lineCap='round';if($('glow').checked){ctx.shadowBlur=14;ctx.shadowColor=color;}ctx.beginPath();active.points.slice(0,pos.i).concat([pos.p]).forEach((p,i)=>ctx[i?'lineTo':'moveTo'](...screen(p)));ctx.stroke();let p=screen(pos.p),radius=+$('size').value/2;ctx.beginPath();ctx.arc(...p,radius,0,2*Math.PI);ctx.fillStyle=color+'28';ctx.fill();ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(...p,3,0,2*Math.PI);ctx.fillStyle=color;ctx.fill();ctx.restore();
// Also draw a small title and credits into the recording itself.
ctx.fillStyle='#e8f0f7';ctx.font='12px system-ui';ctx.fillText('animaTOR · '+active.name,15,h-15);ctx.font='10px system-ui';ctx.textAlign='right';ctx.fillText(base==='satellite'?'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community':base==='osm'?'© OpenStreetMap contributors':'Grade offline',w-12,h-15);ctx.textAlign='left';
$('progress').value=progress*1000;$('play').textContent=playing?'Ⅱ Pausar':'▶ Iniciar';let fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;$('clock').textContent=`${fmt(progress*duration)} / ${fmt(duration)}`;let lat=2*Math.atan(Math.exp(-pos.p[1]/R))-Math.PI/2;$('stats').textContent=`${Math.round(progress*100)}% · ${(active.total*Math.cos(lat)/1000).toFixed(1)} km aprox. · ${tileFailed&&base!=='grid'?'mapa indisponível: use grade offline':follow?'CÂMERA SEGUINDO':'VISTA COMPLETA'}`;requestAnimationFrame(render);}
$('file').onchange=async e=>{let file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('Limite do protótipo: 20 MB.');setData(parseKML(await file.text()));}catch(err){$('status').textContent=err.message;}e.target.value='';};$('track').onchange=selectTrack;$('area').onchange=selectArea;$('demo').onclick=demo;$('reverse').onclick=()=>{active.points.reverse();prepare(active);progress=0;cam=null;selectArea();};$('play').onclick=()=>{if(progress===1)progress=0;playing=!playing;};$('reset').onclick=()=>{playing=false;progress=0;cam=null;};$('progress').oninput=e=>{progress=+e.target.value/1000;playing=false;};$('camera').onchange=()=>cam=null;$('size').oninput=()=>{$('sizeValue').textContent=$('size').value;};$('basemap').onchange=()=>{tileFailed=false;};
$('record').onclick=()=>{if(recorder?.state==='recording'){recorder.stop();return;}if(!canvas.captureStream||!window.MediaRecorder){$('status').textContent='Este navegador não oferece gravação. Use Chrome ou Edge.';return;}try{let type=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!type)throw Error('Gravação WebM indisponível neste navegador.');let stream=canvas.captureStream(30),chunks=[];recorder=new MediaRecorder(stream,{mimeType:type,videoBitsPerSecond:6000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{playing=false;stream.getTracks().forEach(t=>t.stop());let url=URL.createObjectURL(new Blob(chunks,{type})),a=document.createElement('a');a.href=url;a.download='animaTOR.webm';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);$('record').textContent='● Gravar vídeo WebM';};progress=0;cam=null;playing=true;recorder.start();$('record').textContent='■ Encerrar e baixar';$('status').textContent='Gravando. Evite mudar configurações e mantenha a aba visível.';}catch(e){$('status').textContent='Não foi possível gravar: '+e.message;}};
demo();requestAnimationFrame(render);
